services:
  db-api:
    image: timescale/timescaledb:latest-pg15
    container_name: db-api
    restart: unless-stopped
    user: postgres
    # Copiamos la llave privada a /tmp para evitar problemas de permisos de montajes Windows/Linux (chmod 600)
    # y luego ejecutamos postgres con SSL habilitado.
    command: >
      sh -c "
      cp /ssl/server.key /tmp/server.key &&
      chmod 600 /tmp/server.key &&
      exec postgres -c shared_preload_libraries=timescaledb -c ssl=on -c ssl_cert_file=/ssl/server.crt -c ssl_key_file=/tmp/server.key -c ssl_ca_file=/ssl/ca.crt
      "
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_api_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
      - ./db-ssl:/ssl:ro
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_api_data:

networks:
  db-network:
    driver: bridge
